{% set name = "sympow" %}
{% set version = "2.023.7" %}
{% set sha256 = "97ecfe8371bb1ceb827818d41122e09c3a614addc99ec6e241d81a2df2e89b7f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url:  https://salsa.debian.org/science-team/sympow/-/archive/upstream/{{ version }}/sympow-upstream-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0001-OSX-apparently-does-not-know-about-t.patch

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports:
    - pari

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
    - autoconf
    - automake
    - help2man
  host:
    - pari
  run:
    # new_data invokes PARI's GP
    - pari

test:
  commands:
    - sympow -help
    - sympow -new_data 2

about:
  home: http://files.sagemath.org/spkg/upstream/sympow/index.html
  license: BSD-variant
  license_family: BSD
  license_file: {{ SRC_DIR }}/COPYING
  summary: A package to compute special values of symmetric power elliptic curve L-functions

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
