{% set name = "sympow" %}
{% set version = "2.023.3" %}
{% set sha256 = "1ab0297b6ea1516066300bc30f8db6c3c6e66f5d2cfce7cb8ffe38b65d089724" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url:  https://salsa.debian.org/science-team/sympow/-/archive/upstream/{{ version }}/sympow-upstream-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]
  ignore_run_exports:
    - pari

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pari
  run:
    # new_data invokes PARI's GP
    - pari

test:
  commands:
    - sympow -help
    - sympow -new_data 2

about:
  home: http://files.sagemath.org/spkg/upstream/sympow/index.html
  license: BSD-variant
  license_family: BSD
  license_file: {{ SRC_DIR }}/COPYING
  summary: A package to compute special values of symmetric power elliptic curve L-functions

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
