{% set name = "sympow" %}
{% set version = "2.023.6" %}
{% set sha256 = "c014cb8213ff887951b57e7372511ab3e4a96587f3a67bbcb5bd01e8cb3e5be9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://salsa.debian.org/science-team/sympow/-/archive/upstream/{{ version }}/sympow-upstream-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0000-cross.patch
    - 0001-Use-gp-from-environment.patch

build:
  number: 4
  skip: true  # [win]
  ignore_run_exports:
    - pari

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - libtool
    - autoconf
    - automake
    - help2man
    - make
    - pari  # [build_platform != target_platform]
  host:
    - pari
  run:
    # new_data invokes PARI's GP
    - pari

test:
  commands:
    - sympow -help
    - sympow -new_data 2

about:
  home: http://files.sagemath.org/spkg/upstream/sympow/index.html
  license: LicenseRef-BSD-like
  license_family: BSD
  license_file: {{ SRC_DIR }}/COPYING
  summary: A package to compute special values of symmetric power elliptic curve L-functions

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
