{% set name = "sympow" %}
{% set version = "2.023.3" %}
{% set sha256 = "a03fba6b84c83b1317ae9b4fe8eba67132229c9a1982426c0915f963b5ba674e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url:  https://salsa.debian.org/science-team/sympow/-/archive/upstream/{{ version }}/sympow-upstream-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0001-OSX-apparently-does-not-know-about-t.patch

build:
  number: 1003
  skip: true  # [win]
  ignore_run_exports:
    - pari

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
    - autoconf
    - automake
    - help2man
  host:
    - pari
  run:
    # new_data invokes PARI's GP
    - pari

test:
  commands:
    - sympow -help
    - sympow -new_data 2

about:
  home: http://files.sagemath.org/spkg/upstream/sympow/index.html
  license: BSD-variant
  license_family: BSD
  license_file: {{ SRC_DIR }}/COPYING
  summary: A package to compute special values of symmetric power elliptic curve L-functions

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
