travis:
  secure:
    BINSTAR_TOKEN: bZrsFri996JD/yHQfISoO2u+GOVXGuW+GniRQeKADt0yY6i8kAlRZkxKVEzl5GmFp0AZvyhi96AHwoYvzUJIt2R3eY7vO2siIq4hScRt0ZEshAz/WE//REjVgYU509UR15mpuX2cZ7VTsXE4/CicGALuGou2FFVGonXLo7x6bUsD8NdBYSRSY6mI7K/V1Zi230KtdmB8rfq8wHIQtysG9J3pgGMygkzOR3Y1c8zbZ2f1T8b4bhTL3uLtV5QQZ6jiSvTinl2haVgSm16xlvQ27hEqa7dSbhzsQ/VEVqBFO1uwDRYhjwAaF1r5HyvTYa2hL11EQqEfps6nYWCl2E8Tcu2Y6M9JGWbMdo9TdVqOcRihwHvKISlOrvNDGsdWuLPbugE5IvG6aRH/19yYI3ad5CMn2Tm61OyuO2keQl32P8CNU1vmzv8YFQk4LC2EHVTn4Bp0p/JP3yDmDCrRpSwMCRr7XmqSnKAr4LIoc4SA27rTBK6dtWdbwejLRWzn4eZkVkmfnATrnb/nmGLsfOIhgV44mS5seWUaxPX4d/EgKHGGAoMLl6meCG+cSWCtLO1r3+LKNdmLuL+FIUjECvsk86YwWWdObPoA8jSF6h5xaFYA+W+v/KhpMAnwo3TyJeEAJl/nQKHGTQxgXI4V3QRMJy9ZQ+rXVM90f/Hnq3eKUtc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
