appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: ebz8kggi2nJVelG42era7AJ+bNcz4JY+RVLrAcXS6BTXHvh0yD0sJc6wGzD0/uInc63eyUn35LUXxWAkwrwzdnD8OOIHuLKMoSQEIR3vpiRgZXcupotqjWDeNp4DYdSuWnkPd/j+gOhJtFZDGjrjGfbKru2YPRyPTyHjzXxGrANLt+QRXDQsJHqZK7MgS5GdjFLFAzhVllI6e6JLcT+EKA2NVapTwyw8CWDKhuOynM36cAq3+cSdZzSPRoGafUesARyC6R/c8rlzFKRiTc+BUl9Zu27DTbhqg8EeCxD00erBicjJ1CeeDXvbj+9xteymix5guM6cl/aDVCpBAdiOdYGfHp+EYArnGYajN2JMXKbBRa9jX2UElIYjMatRmSNompOBAQKhGXN+yMNynZnpRF7Z2yE+O8T9Ji3i9pI8fMIQTGA/S9iOuBcNJJdOkHks2ADyoNgpSnSw5Hyg8Er2Iu9B32wiE4xIao2z4mn1rCDsUxh5ovFKI6qZ7hz29d7I+PTC7YvTdTD54kb/ua8UV+dl6EAZYXU3H+80pEN3Xk02We4Ht142jYmb2ZAodV9GLShWg6FooJgaVNnAjN7juh9IlHJ8t05ALQkTZKmpMaRoYFF+h7IyH2MXrtLAJ+VB1RlUi+T9Sa8mEKDSfE/RwretZp1yCVc2TaBAtbzBzoU=}
conda_forge_output_validation: true
